import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { ThirdwebProvider } from "./config/thirdweb"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <ThirdwebProvider>{children}</ThirdwebProvider>
}
